// Single schema entry point for the `db` client, the Better Auth adapter and
// drizzle-kit. ./auth is generated by `npm run auth:generate` — never edit it.
export * from "./catalog";
export * from "./auth";
