-- Enforce `user.role` values in the DB. schema/auth.ts is generated by the
-- Better Auth CLI (its text enum is TypeScript-only), so the check lives here.
ALTER TABLE "user" ADD CONSTRAINT "user_role_check" CHECK ("role" IN ('customer', 'admin'));
